### ISSUE TITLE
Icons: ikoner kan ikke gjøres universelt utformet

### ISSUE THREAD

**Issue by terjesyl** [fellesdatakatalog/fdk-kit#128]
Slik ikonene transformeres til React-komponenter nå er det svært vanskelig å gjøre dem tilgjengelig i koden hvor de brukes. Man kan for eksempel ikke sette et `title`-element som skjermlesere kan bruke.

Eksempel på ønsket resultat (etter rendering):
```
<svg>
   <title>Beskrivelse av ikon</title>
   ...
</svg>
```

**Comment by jeffreiffers** [comment]
Antar denne løses av https://github.com/fellesdatakatalog/fdk-kit/issues/160?

**Comment by terjesyl** [comment]
Ja, det er godt mulig! Lukker nå så får vi gjenåpne dersom vi kommer over problemet på nytt.
