### ISSUE TITLE
Storybook registrerer kun ett ikon til review og baseline oppdateres ikke.

### ISSUE THREAD

**Issue by terjesyl** [fellesdatakatalog/fdk-kit#82]
Ved review i chromatic dukker kun 'check'-ikonet opp, selv om det ikke har vært noen endringer i det. Det ser ikke ut til at ny ikoner lagt til i assets registreres av chromatic.

**Comment by terjesyl** [comment]
Det ser heller ikke ut til at baseline blir oppdatert.

**Comment by valosnah** [comment]
Er muligens noe forklaring her
https://www.chromatic.com/docs/branching-and-baselines#how-baselines-are-calculated

**Comment by terjesyl** [comment]
Fikset vi ikke denne med https://github.com/fellesdatakatalog/fdk-kit/pull/91 @valosnah

**Comment by terjesyl** [comment]
fixed by #91
